# This is a basic workflow to help you get started with Actions

name: Generate-Metrics

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 */6 * * *" 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Generate 3D Metric
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 300

      # 移动生成结果到 assets/profile-3d
      - name: Move generated 3D profile to assets/profile-3d
        run: |
          mkdir -p assets/profile-3d
          mv profile-3d-contrib/* assets/profile-3d/
          rm -rf profile-3d-contrib
    
      - name: Configure Git and Push Changes to main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/profile-3d/
          git rm -r --ignore-unmatch profile-3d-contrib
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: update 3d profile"
          git push origin main 
          
      - name: WakaTime Metric
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.svg
          base: header, repositories
          plugin_wakatime: yes
          token: ${{ secrets.GH_TOKEN }}
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_user: h2sxxa
          plugin_wakatime_sections: time, languages, languages-graphs, editors, editors-graphs, os
